# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0531493940017ad64e85c7475049842897d1cbf869904f4442d5482617c65a6c5a065e87509628841fad7636cc0284a5fc270f3fe70a7bd98a1149ca7559c22

test:
  secret_key_base: 643121b1d4e266ada25711917887244eb089245ac7337727728249e66d89da3aef3cc06187f9c9f0c651367ada1334f5a72115190227de133fcbab2501dd5dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
